### ISSUE TITLE
Player Features and needs

### ISSUE THREAD

**Issue by SrPatinhas** [DreaMovies/desktop-uploader#5]
At the moment we are using [VideoJS 7](https://videojs.com/) but there is a replacement in case of need [Plyr](https://plyr.io/) but the code base would need to be rewrite.

For now, this is what is needed to do 

**Tasks**

- [ ] Loading screen before player to start load content when needed
- [ ] Subtitles management and pre-configuration (background and font for example)
- [ ] External play 
  - [ ]  Chromecast
  - [ ] AirPlay
  - [ ] External Players (VLC, or any other that is installed in the system)
- [ ] Play next episode 
- [ ] Auto create a Queue when possible or just give some suggestions
- [ ] Change Quality if possible
- [ ] Have more Codecs
